//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCode.SmartObjects.Services.Tests.UTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceCode.SmartObjects.Services.Tests.UTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;serviceinstance name=&quot;URMService&quot; type=&quot;SourceCode.SmartObjects.Services.UserRoleManagerService.URMService&quot; guid=&quot;4C2F62EA-BE8D-4600-A2B5-185902BDD20A&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;URM Service&lt;/displayname&gt;
        ///      &lt;description&gt;URM Service from User and Group resolution against labels&lt;/description&gt;
        ///    &lt;/display&gt;
        ///    &lt;service /&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;serviceobject /&gt;
        ///  &lt;servicefolder&gt;
        ///    &lt;folders /&gt;
        ///  &lt;/servicefolder&gt;
        ///  &lt;serviceextend&gt;
        ///    &lt;objects /&gt;
        ///  &lt;/serviceextend&gt;
        ///  &lt;servic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceInstance_URMService {
            get {
                return ResourceManager.GetString("ServiceInstance_URMService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;serviceinstance name=&quot;URMService&quot; guid=&quot;4c2f62ea-be8d-4600-a2b5-185902bdd20a&quot; type=&quot;SourceCode.SmartObjects.Services.UserRoleManagerService.URMService&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;URM Service&lt;/displayname&gt;
        ///      &lt;description&gt;URM Service from User and Group resolution against labels&lt;/description&gt;
        ///    &lt;/display&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;serviceobject&gt;
        ///    &lt;objects&gt;
        ///      &lt;object name=&quot;Group&quot; type=&quot;&quot; active=&quot;true&quot; version=&quot;&quot;&gt;
        ///        &lt;metadata&gt;
        ///          &lt;display&gt;
        ///            &lt;displayna [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceInstance_URMService_Full {
            get {
                return ResourceManager.GetString("ServiceInstance_URMService_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;serviceconfig&gt;
        ///  &lt;serviceauthentication securityprovider=&quot;&quot; oauthresourcename=&quot;&quot; oauthresourceaudience=&quot;&quot; impersonate=&quot;true&quot; isrequired=&quot;false&quot; enforceimpersonation=&quot;false&quot; useoauth=&quot;false&quot;&gt;
        ///    &lt;username /&gt;
        ///    &lt;password /&gt;
        ///    &lt;extra /&gt;
        ///    &lt;oauthtoken /&gt;
        ///  &lt;/serviceauthentication&gt;
        ///  &lt;settings /&gt;
        ///&lt;/serviceconfig&gt;.
        /// </summary>
        internal static string ServiceInstanceConfig {
            get {
                return ResourceManager.GetString("ServiceInstanceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;serviceinstances&gt;
        ///  &lt;serviceinstance name=&quot;URMService&quot; type=&quot;SourceCode.SmartObjects.Services.UserRoleManagerService.URMService&quot; guid=&quot;4C2F62EA-BE8D-4600-A2B5-185902BDD20A&quot;&gt;
        ///    &lt;metadata&gt;
        ///      &lt;display&gt;
        ///        &lt;displayname&gt;URM Service&lt;/displayname&gt;
        ///        &lt;description&gt;URM Service from User and Group resolution against labels&lt;/description&gt;
        ///      &lt;/display&gt;
        ///      &lt;service /&gt;
        ///    &lt;/metadata&gt;
        ///    &lt;serviceobject /&gt;
        ///    &lt;servicefolder&gt;
        ///      &lt;folders /&gt;
        ///    &lt;/servicefolder&gt;
        ///    &lt;serviceextend&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceInstancesCompact_URMService {
            get {
                return ResourceManager.GetString("ServiceInstancesCompact_URMService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;object name=&quot;ProcessOverview&quot; type=&quot;processOverview&quot; version=&quot;&quot; active=&quot;true&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;Process Overview&lt;/displayname&gt;
        ///      &lt;description /&gt;
        ///    &lt;/display&gt;
        ///    &lt;service /&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;properties&gt;
        ///    &lt;property name=&quot;ProcessSetID&quot; type=&quot;System.Int32&quot; extendtype=&quot;default&quot; sotype=&quot;number&quot;&gt;
        ///      &lt;metadata&gt;
        ///        &lt;display&gt;
        ///          &lt;displayname&gt;Process Set ID&lt;/displayname&gt;
        ///          &lt;description /&gt;
        ///        &lt;/display&gt;
        ///        &lt;service&gt;
        ///          &lt;key  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceObject_ProcessOverview {
            get {
                return ResourceManager.GetString("ServiceObject_ProcessOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;servicetype name=&quot;SourceCode.SmartObjects.Services.AD.ADService&quot; guid=&quot;5c50e5ca-985d-49db-8486-cf8dfb702dac&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;AD Service2&lt;/displayname&gt;
        ///      &lt;description /&gt;
        ///    &lt;/display&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;config&gt;
        ///    &lt;assembly path=&quot;C:\Program Files (x86)\K2\ServiceBroker\SourceCode.SmartObjects.Services.ADService.dll&quot; class=&quot;SourceCode.SmartObjects.Services.AD.ADService&quot; /&gt;
        ///  &lt;/config&gt;
        ///&lt;/servicetype&gt;.
        /// </summary>
        internal static string ServiceType_ADService {
            get {
                return ResourceManager.GetString("ServiceType_ADService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;smartobjectroot name=&quot;K2_Management_WebDesigner_Management_ProcessInfo&quot; guid=&quot;8cfa08b3-92e6-4317-93d9-376737f0f982&quot; version=&quot;0&quot; isextendible=&quot;false&quot; mode=&quot;advanced&quot; createdfromlocal=&quot;false&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;ProcessInfo&lt;/displayname&gt;
        ///      &lt;description /&gt;
        ///    &lt;/display&gt;
        ///    &lt;service&gt;
        ///      &lt;key name=&quot;serviceinstance&quot;&gt;5d273ad6-e27a-46f8-be67-198b36085f99&lt;/key&gt;
        ///      &lt;key name=&quot;serviceobject&quot;&gt;WebDesigner_Management_ProcessInfo&lt;/key&gt;
        ///    &lt;/service&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartObjectDefinition_ProcessInfo {
            get {
                return ResourceManager.GetString("SmartObjectDefinition_ProcessInfo", resourceCulture);
            }
        }
    }
}
