//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCode.SmartObjects.Services.Tests.UTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceCode.SmartObjects.Services.Tests.UTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;serviceinstance name=&quot;URMService&quot; type=&quot;SourceCode.SmartObjects.Services.UserRoleManagerService.URMService&quot; guid=&quot;4C2F62EA-BE8D-4600-A2B5-185902BDD20A&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;display&gt;
        ///      &lt;displayname&gt;URM Service&lt;/displayname&gt;
        ///      &lt;description&gt;URM Service from User and Group resolution against labels&lt;/description&gt;
        ///    &lt;/display&gt;
        ///    &lt;service /&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;serviceobject /&gt;
        ///  &lt;servicefolder&gt;
        ///    &lt;folders /&gt;
        ///  &lt;/servicefolder&gt;
        ///  &lt;serviceextend&gt;
        ///    &lt;objects /&gt;
        ///  &lt;/serviceextend&gt;
        ///  &lt;servic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceInstance_URMService {
            get {
                return ResourceManager.GetString("ServiceInstance_URMService", resourceCulture);
            }
        }
    }
}
