version: 1.0.{build}

image: Visual Studio 2017

configuration:
- Release

platform: Any CPU

before_build:
- nuget restore -verbosity quiet

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal

test_script:
- vstest.console /logger:Appveyor /Settings:src\AppVeyor.RunSettings /InIsolation "src\Tests\UTest\bin\Release\SourceCode.SmartObjects.Services.Tests.UTest.dll"

# build NuGet package and upload it to artifacts
after_build:
- nuget pack src\SourceCode.SmartObjects.Services.Tests.nuspec -Version %appveyor_build_version%

artifacts:
- path: SourceCode.SmartObjects.Services.Tests.%appveyor_build_version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: 9ZjxrStO3j210yUXmH4Q5/H7Bkepb+A1f3kn0snparetNCiXA7sYHvQLRVlAt94m
  on:
    branch: master
