version: 1.0.{build}

image: Visual Studio 2017

assembly_info:
  patch: true
  file: 'src\Properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true  

configuration:
- Release

platform: Any CPU

# scripts to run before build
before_build:
- nuget restore -verbosity quiet

build:
 project: SourceCode.SmartObjects.Services.Tests.sln
 verbosity: minimal
 publish_nuget: true             # package projects with .nuspec files and push to artifacts

test_script:
- vstest.console /logger:Appveyor /Settings:src\AppVeyor.RunSettings /InIsolation "src\Tests\UTest\bin\Release\SourceCode.SmartObjects.Services.Tests.UTest.dll"

after_build:
- ps: Add-AppveyorMessage "NuGet artifact not deployed. Version. $env:APPVEYOR_BUILD_VERSION" -Category "Information" -Details "The NuGet package is not published automatically, but can be published through the AppVeyor Deploy UI."

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: IlYToFQdqCxXKG7TERDXxDioFSN74Bp5Cmkv4VsemoPxQj3IOsx5t0wCxRzFslPR
#  on:
#    branch: master
